# Observability Config
environment: "dev"

metrics:
  address: ":2112"

bulkhead:
  capacity: 1
  timeout: 5s

logger:
  log_level: "INFO"

tracing:
  service_name: "Goletan core"
  exporter: "http://opentelemetry-collector.default:4317"
  sampling_ratio: 3.14
