discovery:
  strategies:
    - name: kubernetes
      namespace: goletan-services
    - name: docker
      network: goletan_services_network
    - name: dns
      domain: example.local
  default_strategy: kubernetes
